#!/usr/bin/perl
#!/usr/local/bin/perl

################################################################
#             Copyright (C) 1998-present ECE Dept.             #
#                  Carnegie Mellon University                  #
################################################################

use strict;

my $program = $0;
$program =~ s/.*\///;

use Getopt::Long;

sub usage {
  warn " $program: @_ \n" if @_;
  print " Usage: $program <circuit-file> <tester-file> <ssl-faults-file> <test-set-file>\n\n";
  print "  <circuit-file> \tFile containing the circuit description\n";
  print "  <tester-file> \tFile containing the tester responses\n";
  print "  <ssl-faults-file>\tSSL faults for simulation (file format as required by ganga)\n";
  print "  <test-set-file>\tTests for simulation (file format as required by ganga)\n\n";
  print " OPTIONS:\n";
  print "  --ganga <DIR>\t\tLocation of ganga binary (default: /afs/ece/class/ee765/projects/bin)\n";
  print "  --output <FILE>\tStore the results in <file> (default: stdout)\n";
  print "  --help\t\tPrint this online help and quit\n\n";
  print " This script can be used to perform simulation of SSL faults and\n";
  print " compare the resultant response files with the tester responses.\n";
  die "\n";
}

# Default values
my $ganga_directory = "./env";
my $output = "";
my $help = 0;

GetOptions(
	   "output=s"   => \$output,
	   "help"       => \$help,
	  ) || die " $program: Try -h or --help option for more information\n";

if ($help) {
  usage;
}

if (@ARGV < 4) {
  print " $program: The circuit, tester, ssl-faults or test set file not provided\n";
  die " $program: Try -h or --help option for more information\n";
}

my $circuit_file = shift(@ARGV);
my $tester_file = shift(@ARGV);
my $ssl_faults_file = shift(@ARGV);
my $testset_file = shift(@ARGV);

my @ssl_faults = ();
open(RH, "$ssl_faults_file") or die " $program: Could not open SSL faults file\n";
while(<RH>) {
  if ($_ =~ /(\d+):\s+(\w+->\w+|\w+)\s+(\w+)/) {
    push(@ssl_faults, "$2 $3");
  }
}
close(RH);

my $circuit_name = $circuit_file;
$circuit_name =~ s/.*\///;
$circuit_name =~ /(.*)\..*/;
$circuit_name = $1;

# Perform simulation
my $ganga_command = "${ganga_directory}/ganga $circuit_file --ssls ${ssl_faults_file} --test ${testset_file} --diagnosis";
my $ganga_results = `${ganga_command}`;

my $file_handle;

if ($?) {
  die " $program: Error while running ganga, please check files used for simulation.\n";
}
else {
  # Simulation was successful

  # The output file
  if ($output) {
    open(OUTFILE, "> $output") or die " $program: Could not open $output for writing\n";
    $file_handle = \*OUTFILE;
  }
  else {
    $file_handle = \*STDOUT;
  }

  # Compare the responses of the tester with responses of each SSL fault

  # Parse the tester file
  my %tester = parse_response_file($tester_file);

  # Statistics about tester responses
  print $file_handle " Details of the tester responses:-\n";
  print_details(%tester);

  print $file_handle "\n";
  for (my $i = 0; $i < @ssl_faults; $i++) {
    print $file_handle " For SSL fault: $ssl_faults[$i]\n";

    my $ssl_response_file = "results/responses/${circuit_name}/".($i+1).".resp";
    my %ssl_responses = parse_response_file($ssl_response_file);

    my @results = compare_dictionaries(\%tester, \%ssl_responses);

    printf $file_handle "  Number of matches   : %5d\n", $results[0];
    printf $file_handle "  Number of mismatches: %5d\n", $results[1];
    print $file_handle "\n";
  }
}

if ($output) {
  close(OUTPUT);
}

##
# Sub-routines
##

sub parse_response_file {
  my $file = shift;

  my %responses = ();

  open(RH, "$file") or die " $program: Could not open response file $file\n";
  while (<RH>) {
    if ($_ =~ /\s*(\d+)\s*:\s*([01]+)\s+([01]+)\s+([01]+)/) {
      my $pi = $2;
      my $good = $3;
      my $faulty = $4;

      $responses{$1}{pi} = $pi;
      $responses{$1}{good} = $good;
      $responses{$1}{actual} = $faulty;
    }
  }
  close(RH);

  return (%responses);
}

# Print the details of a set of responses
sub print_details {
  my %responses = @_;
  my $fp = 0;
  my $pp = keys %responses;

  printf $file_handle "  Total number of patterns applied: %5d\n", $pp;
  print $file_handle "   Failures at POs for patterns:-\n";
  foreach (sort {$a <=> $b} keys %responses) {
    my @results = compare_responses($responses{$_}{good}, $responses{$_}{actual});
    my $result = shift(@results);

    if (!($result)) {
      $fp++;
      $pp--;
    }

    printf $file_handle "    #%2d: @results\n", $_;
  }

  printf $file_handle "  Total number of failing patterns: %5d\n", $fp;
  printf $file_handle "  Total number of passing patterns: %5d\n", $pp;
}

# Compare two responses
sub compare_responses {
  my @r1bits = split(//, $_[0]);
  my @r2bits = split(//, $_[1]);

  my $result = 1;
  my $i = 0;
  my @pos = ();

  # print "Comparing @r1bits and @r2bits\n";
  while ($i < @r1bits) {
    if ($r1bits[$i] ne $r2bits[$i]) {
      $result = 0;
      push (@pos, $i);
    }

    $i++;
  }

  return ($result, @pos);
}

# Compare a tester response with SSL dictionary
sub compare_dictionaries {
  no strict 'refs';

  my %tester_dictionary = %{@_[0]};
  my %ssl_dictionary = %{@_[1]};

  my $patterns_matched = 0;
  my $patterns_mismatched = 0;

  # Compare the dictionaries for all patterns
  foreach my $pattern (sort {$a <=> $b} keys %tester_dictionary) {
    my @results = compare_responses($tester_dictionary{$pattern}{actual}, $ssl_dictionary{$pattern}{actual});
    my $result = shift(@results);

    if ($result) {
      # Matching ok
      $patterns_matched++;
    }
    else {
      $patterns_mismatched++;
    }
  }

  return ($patterns_matched, $patterns_mismatched);
}
